[tool.coverage.run]
branch = true
source = [ "src" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../../coverage/libs/shared/hermes-db/html'
 --cov-report xml:'../../../coverage/libs/shared/hermes-db/coverage.xml'
 --html='../../../reports/libs/shared/hermes-db/unittests/html/index.html'
 --junitxml='../../../reports/libs/shared/hermes-db/unittests/junit.xml'
"""

[project]
name = "hermes-db"
version = "1.0.0"
description = "shared postgis + pgvector database models for hermes."
requires-python = ">=3.14"
readme = 'README.md'
dependencies = [
  "asyncpg>=0.31.0",
  "geoalchemy2>=0.17.1",
  "pgvector>=0.4.2",
  "sqlalchemy>=2.0.51",
  "alembic>=1.16.5",
  "pydantic-settings>=2.11.0",
  "python-dotenv>=1.2.1",
  "greenlet>=3.5.6",
]


[dependency-groups]
dev = [
  "autopep8>=2.3.1",
  "ruff>=0.8.2",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "pytest-html>=4.1.1",
]

[build-system]
requires = ["uv_build>=0.8.9,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 88
indent-width = 4
exclude = [
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "dist",
  "migrations",
]


[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]
ignore = ["E501"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["src"]

[tool.pyright]
typeCheckingMode = "basic"
extraPaths = ["src"]
