[tool.coverage.run]
branch = true
source = [ "src" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../../coverage/libs/shared/hermes-ai/html'
 --cov-report xml:'../../../coverage/libs/shared/hermes-ai/coverage.xml'
 --html='../../../reports/libs/shared/hermes-ai/unittests/html/index.html'
 --junitxml='../../../reports/libs/shared/hermes-ai/unittests/junit.xml'
"""

[project]
name = "hermes-ai"
version = "1.0.0"
description = "shared ai and llm abstraction library for hermes."
requires-python = ">=3.14"
readme = 'README.md'
dependencies = [
  "httpx>=0.28.1",
  "litellm>=1.83.0",
  "pydantic>=2.14.0",
]

[dependency-groups]                                        
dev = [                                                    
  "ruff>=0.8.2",                                         
  "pytest>=8.3.4",                                       
  "pytest-sugar>=1.0.0",                                 
  "pytest-cov>=6.0.0",                                   
  "pytest-html>=4.1.1",                                  
]


[build-system]
requires = ["uv_build>=0.8.9,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
exclude = [
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "dist",
]

line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]
ignore = ["E501"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["src"]
