services:
  hermes-db:
    build:
      context: .
      dockerfile_inline: |
        FROM postgis/postgis
        RUN apt-get update \
            && apt-get install -y --no-install-recommends postgresql-$$PG_MAJOR-pgvector \
            && rm -rf /var/lib/apt/lists/*
    restart: always
    env_file:
      - .env.development
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - hermes_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5

  hermes-api:
    build:
      context: .
      dockerfile: apps/hermes-api/Dockerfile
      target: development
    ports:
      - '${API_PORT}:8000'
    volumes:
      - ./apps/hermes-api/src:/app/apps/hermes-api/src
      - ./libs/shared/hermes-db/src:/app/libs/shared/hermes-db/src
      
    env_file:
      - .env.development
      - path: ./apps/hermes-api/.env.development
        required: false
      - path: ./apps/hermes-api/.env.local
        required: false
    depends_on:
      hermes-db:
        condition: service_healthy
    restart: unless-stopped

  hermes-worker:
    build:
      context: .
      dockerfile: apps/hermes-worker/Dockerfile
      target: development
    volumes:
      - ./apps/hermes-worker/src:/app/apps/hermes-worker/src
    env_file:
      - .env.development
      - path: ./apps/hermes-worker/.env.development
        required: false
      - path: ./apps/hermes-worker/.env.local
        required: false
      - path: ./apps/hermes-api/.env.development
        required: false
      - path: ./apps/hermes-api/.env.local
        required: false
    depends_on:
      hermes-db:
        condition: service_healthy
    profiles: ["worker"]

  hermes:
    build:
      context: .
      dockerfile: apps/hermes/Dockerfile
      target: development
    ports:
      - '${FRONTEND_PORT}:4200'
    volumes:
      - ./apps/hermes/app:/app/apps/hermes/app
      - ./apps/hermes/styles.css:/app/apps/hermes/styles.css
      - ./apps/hermes/public:/app/apps/hermes/public
      - ./libs:/app/libs
    env_file:
      - .env.development
      - path: ./apps/hermes/.env.development
        required: false
      - path: ./apps/hermes/.env.local
        required: false
    environment:
      HOST: 0.0.0.0
    restart: unless-stopped


volumes:
  hermes_data:
