"""teardown_old_lineage

Revision ID: 64fc96ec0afd
Revises: db402a499ebd
Create Date: 2026-09-17 15:32:41.817535

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64fc96ec0afd"
down_revision: Union[str, Sequence[str], None] = "db402a499ebd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "ALTER TABLE events DROP CONSTRAINT IF EXISTS fk_events_lineage_target_id;"
    )
    op.execute("ALTER TABLE events DROP COLUMN IF EXISTS lineage_target_id;")
    op.execute("ALTER TABLE events DROP COLUMN IF EXISTS has_lineage;")

    op.execute("DROP TABLE IF EXISTS event_edges CASCADE;")
    op.execute("DROP TABLE IF EXISTS event_timelines CASCADE;")
    op.execute("DROP TABLE IF EXISTS story_allowlists CASCADE;")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "has_lineage",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "events",
        sa.Column("lineage_target_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_events_lineage_target_id"),
        "events",
        "events",
        ["lineage_target_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
