"""create event_edges table

Revision ID: ce3d9051b570
Revises: d159bcfd1e94
Create Date: 2026-09-14 17:32:49.119905

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce3d9051b570"
down_revision: Union[str, Sequence[str], None] = "d159bcfd1e94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_edges",
        sa.Column("event_a_id", sa.Uuid(), nullable=False),
        sa.Column("event_b_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("event_a_id != event_b_id", name="check_no_self_edge"),
        sa.ForeignKeyConstraint(["event_a_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_b_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_a_id", "event_b_id", "relationship_type", name="uq_event_edge"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_edges")
    # ### end Alembic commands ###
