"""initial schema.

Revision ID: 2ec3541646e8
Revises: 
Create Date: 2026-08-21 21:24:20.891566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '2ec3541646e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('events',
    sa.Column('ai_headline', sa.String(length=500), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('category_color', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STALE', 'ARCHIVED', name='eventstatus'), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'COUNTRY', 'STATE', 'CITY', 'LOCAL', name='eventscope'), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('trending_score', sa.Float(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('first_reported_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_active_score', 'events', ['status', 'trending_score'], unique=False, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('idx_events_country', 'events', ['country_code'], unique=False, postgresql_where=sa.text('country_code IS NOT NULL'))
    op.create_geospatial_index('idx_events_location', 'events', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_events_scope', 'events', ['scope', 'status'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('RSS', 'API', 'SCRAPE', name='sourcetype'), nullable=False),
    sa.Column('credibility', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', name='credibilitytier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('articles',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('sources')
    op.drop_index('idx_events_scope', table_name='events')
    op.drop_geospatial_index('idx_events_location', table_name='events', postgresql_using='gist', column_name='location')
    op.drop_index('idx_events_country', table_name='events', postgresql_where=sa.text('country_code IS NOT NULL'))
    op.drop_index('idx_events_active_score', table_name='events', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_geospatial_table('events')
    # ### end Alembic commands ###
