"""teardown_old_lineage

Revision ID: 64fc96ec0afd
Revises: db402a499ebd
Create Date: 2026-09-17 15:32:41.817535

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '64fc96ec0afd'
down_revision: Union[str, Sequence[str], None] = 'db402a499ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_events_lineage_target_id'), 'events', type_='foreignkey')
    op.drop_column('events', 'lineage_target_id')
    op.drop_column('events', 'has_lineage')
    
    op.drop_table('event_edges')
    op.drop_table('event_timelines')
    op.drop_table('story_allowlists')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('has_lineage', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('lineage_target_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_events_lineage_target_id'), 'events', 'events', ['lineage_target_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
