"""made event location nullable.

Revision ID: b8446b410d52
Revises: 2ec3541646e8
Create Date: 2026-08-27 23:02:18.657382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'b8446b410d52'
down_revision: Union[str, Sequence[str], None] = '2ec3541646e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'location',
               existing_type=Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=True)
    op.alter_column('events', 'location_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'location_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('events', 'location',
               existing_type=Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=False)
    # ### end Alembic commands ###
